---
- name: Install and start OpenCanary honeypot instance
  hosts: localhost
 
  tasks:
  - name: Include variables
    include_vars: "{{ item }}.yml"
    loop:
      - secrets/mail_secret
      - vars/user
      - vars/services

  - name: Install OpenCanary
    import_tasks: tasks/install_honeypot.yml

  - name: Start OpenCanary
    import_tasks: tasks/start_honeypot.yml
