---
- name: Install and start OpenCanary honeypot instance
  hosts: localhost
 
  tasks:
  - name: Include variables
    include_vars: "{{ item }}"
    loop:
      - secrets/mail_secret.yml
      - vars/user.yml
      - vars/services.yml

  - name: Install OpenCanary
    import_tasks: tasks/install_honeypot.yml

  - name: Start OpenCanary
    import_tasks: tasks/start_honeypot.yml
