---
- name: Install required apt packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - virtualenv

- name: Create a Python3 virtual environment
  command:
    cmd: virtualenv -p python3 "{{ venv_path }}"
    creates: "{{ venv_path }}"

- name: Install specified Python packages
  pip:
    name: opencanary
    virtualenv: "{{ venv_path }}"
