---
- name: Create /etc/opencanary directory
  file:
    path: /etc/opencanaryd
    state: directory
    mode: "0755"

- name: Generate a OpenCanary conf file
  template:
    src: ../templates/opencanary.conf.j2
    dest: /etc/opencanaryd/opencanary.conf
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Start OpenCanary daemon
  script:
    cmd: ../helper_scripts/activate.sh "{{ venv_path }}"
