---
- name: Start OpenCanary honeypot
  hosts: localhost

  tasks:
  - name: Include secrets
    include_vars: ../secrets/mail_secret.yml

  - name: Create /etc/opencanary directory
    file:
      path: /etc/opencanaryd
      state: directory
      mode: "0755"

  - name: Generate a OpenCanary conf file
    template:
      src: ../opencanary.conf.j2
      dest: /etc/opencanaryd/opencanary.conf
      owner: honey
      group: honey
      mode: "0644"

  - name: Start OpenCanary daemon
    script:
      cmd: ../activate.sh

